version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    container_name: qxt-kafka-zoo
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    build: .
    container_name: qxt-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: qxt-kafka-zoo:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock